import type { GalleryImage } from "@/types";

/**
 * Gallery image manifest. Each `src` points at the exact file the design
 * expects — see MEDIA_CHECKLIST.md for filenames, dimensions and subject
 * guidance. Until a real file exists at that path, <EditorialImage> renders
 * a tasteful placeholder automatically, so this list can be wired up ahead
 * of final photography and will improve the moment files are dropped in.
 */
export const galleryImages: GalleryImage[] = [
  {
    id: "wedding-01",
    src: "/images/gallery/wedding-01.jpg",
    alt: "Marquee reception with a cascading greenery installation above long banquet tables",
    caption: "Hanging greenery installation",
    category: "weddings",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "wedding-02",
    src: "/images/gallery/wedding-02.jpg",
    alt: "Mirror disco balls suspended above a floral wedding stage inside a marquee",
    caption: "Disco ball installation",
    category: "weddings",
    orientation: "portrait",
  },
  {
    id: "wedding-03",
    src: "/images/gallery/wedding-03.jpg",
    alt: "Marquee ceremony aisle dressed with florals and drapery",
    caption: "Ceremony styling",
    category: "weddings",
    orientation: "landscape",
  },
  {
    id: "wedding-04",
    src: "/images/gallery/wedding-04.jpg",
    alt: "Clear-roof marquee dressed for a South Asian wedding, with ornate mandap structures and a petal-lined aisle",
    caption: "Ceremony & reception styling",
    category: "weddings",
    orientation: "portrait",
  },
  {
    id: "private-01",
    src: "/images/gallery/private-01.jpg",
    alt: "Garden marquee set up for a private birthday celebration at dusk",
    caption: "Milestone birthday, private garden",
    category: "private-events",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "private-02",
    src: "/images/gallery/private-02.jpg",
    alt: "Lounge furniture and bar area inside a private event marquee",
    caption: "Lounge & bar styling",
    category: "private-events",
    orientation: "portrait",
  },
  {
    id: "private-03",
    src: "/images/gallery/private-03.jpg",
    alt: "Family celebration marquee with themed décor and table settings",
    caption: "Family celebration",
    category: "private-events",
    orientation: "landscape",
  },
  {
    id: "corporate-01",
    src: "/images/gallery/corporate-01.jpg",
    alt: "Clear-span corporate marquee configured for a product launch",
    caption: "Product launch structure",
    category: "corporate",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "corporate-02",
    src: "/images/gallery/corporate-02.jpg",
    alt: "Branded corporate hospitality marquee with bar and lounge seating",
    caption: "Client hospitality suite",
    category: "corporate",
    orientation: "portrait",
  },
  {
    id: "corporate-03",
    src: "/images/gallery/corporate-03.jpg",
    alt: "Rows of seating inside a marquee set for a corporate conference",
    caption: "Conference configuration",
    category: "corporate",
    orientation: "landscape",
  },
  {
    id: "interior-01",
    src: "/images/gallery/interior-01.jpg",
    alt: "Close-up of ceiling drapery and chandelier inside a marquee",
    caption: "Ceiling drape & chandelier",
    category: "interiors",
    orientation: "portrait",
    featured: true,
  },
  {
    id: "interior-02",
    src: "/images/gallery/interior-02.jpg",
    alt: "Textured wall lining and soft furnishing detail inside a marquee",
    caption: "Wall lining detail",
    category: "interiors",
    orientation: "square",
  },
  {
    id: "interior-03",
    src: "/images/gallery/interior-03.jpg",
    alt: "Glass-clear marquee wall showing garden views from inside",
    caption: "Glass-clear structure",
    category: "interiors",
    orientation: "landscape",
  },
  {
    id: "interior-04",
    src: "/images/gallery/interior-04.jpg",
    alt: "Dressed dining table with fine linen and glassware inside a marquee",
    caption: "Table styling detail",
    category: "interiors",
    orientation: "portrait",
  },
  {
    id: "night-01",
    src: "/images/gallery/night-01.jpg",
    alt: "Marquee glowing from within at night, viewed across a garden",
    caption: "Marquee at night",
    category: "night-events",
    orientation: "landscape",
    featured: true,
  },
  {
    id: "night-02",
    src: "/images/gallery/night-02.jpg",
    alt: "Marquee interior with a lighting rig and crystal chandeliers above tables dressed with tall white florals",
    caption: "Lighting rig & chandeliers",
    category: "night-events",
    orientation: "portrait",
  },
  {
    id: "night-03",
    src: "/images/gallery/night-03.jpg",
    alt: "Guests dancing under lighting inside a marquee at night",
    caption: "Dancefloor after dark",
    category: "night-events",
    orientation: "landscape",
  },
  {
    id: "night-04",
    src: "/images/gallery/night-04.jpg",
    alt: "Aerial view of an illuminated marquee on a private estate at night",
    caption: "Aerial view, evening build",
    category: "night-events",
    orientation: "square",
  },
];

export const galleryFilters: { label: string; value: "all" | GalleryImage["category"] }[] = [
  { label: "All", value: "all" },
  { label: "Weddings", value: "weddings" },
  { label: "Private Events", value: "private-events" },
  { label: "Corporate", value: "corporate" },
  { label: "Interiors", value: "interiors" },
  { label: "Night Events", value: "night-events" },
];
